// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/roomly-vibes/Cockpit.tsx": () => import("../components/mockups/roomly-vibes/Cockpit.tsx"),
  "./components/mockups/roomly-vibes/Editorial.tsx": () => import("../components/mockups/roomly-vibes/Editorial.tsx"),
  "./components/mockups/roomly-vibes/WarmHome.tsx": () => import("../components/mockups/roomly-vibes/WarmHome.tsx")
};
