// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/roomly-concepts/HouseScore.tsx": () => import("../components/mockups/roomly-concepts/HouseScore.tsx"),
  "./components/mockups/roomly-concepts/PeopleFirst.tsx": () => import("../components/mockups/roomly-concepts/PeopleFirst.tsx"),
  "./components/mockups/roomly-concepts/SocialFeed.tsx": () => import("../components/mockups/roomly-concepts/SocialFeed.tsx"),
  "./components/mockups/roomly-concepts/TodayMode.tsx": () => import("../components/mockups/roomly-concepts/TodayMode.tsx"),
  "./components/mockups/roomly-layout-vibes/DarkMode.tsx": () => import("../components/mockups/roomly-layout-vibes/DarkMode.tsx"),
  "./components/mockups/roomly-layout-vibes/Playful.tsx": () => import("../components/mockups/roomly-layout-vibes/Playful.tsx"),
  "./components/mockups/roomly-layout-vibes/Prestige.tsx": () => import("../components/mockups/roomly-layout-vibes/Prestige.tsx"),
  "./components/mockups/roomly-vibes/Cockpit.tsx": () => import("../components/mockups/roomly-vibes/Cockpit.tsx"),
  "./components/mockups/roomly-vibes/Editorial.tsx": () => import("../components/mockups/roomly-vibes/Editorial.tsx"),
  "./components/mockups/roomly-vibes/WarmHome.tsx": () => import("../components/mockups/roomly-vibes/WarmHome.tsx"),
  "./components/mockups/roomly-concepts2/Envelopes.tsx": () => import("../components/mockups/roomly-concepts2/Envelopes.tsx"),
  "./components/mockups/roomly-concepts2/HouseAI.tsx": () => import("../components/mockups/roomly-concepts2/HouseAI.tsx"),
  "./components/mockups/roomly-concepts2/HouseCalendar.tsx": () => import("../components/mockups/roomly-concepts2/HouseCalendar.tsx"),
  "./components/mockups/roomly-concepts2/RoomMap.tsx": () => import("../components/mockups/roomly-concepts2/RoomMap.tsx")
};
